---
- name: Enable Hyprland user services
  become: false
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    scope: user
  loop: "{{ hyprland_user_services.enable }}"
  loop_control:
    label: "{{ item }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"

- name: Unmask shared user targets
  become: false
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    masked: false
    scope: user
  loop: "{{ hyprland_user_targets.unmask }}"
  loop_control:
    label: "{{ item }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"

- name: Mask Hyprland user targets
  become: false
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    masked: true
    scope: user
  loop: "{{ hyprland_user_targets.mask }}"
  loop_control:
    label: "{{ item }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"
