general {
    ignore_dbus_inhibit = false
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && sleep 1 && hyprctl dispatch 'hl.dsp.focus({ monitor = "HDMI-A-1" })'
}

listener {
    timeout = 600

    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable", monitor = "HDMI-A-1" })' && hyprctl dispatch 'hl.dsp.dpms({ action = "disable", monitor = "HEADLESS-1" })'

    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable", monitor = "HDMI-A-1" })' && hyprctl dispatch 'hl.dsp.dpms({ action = "enable", monitor = "HEADLESS-1" })' && sleep 1 && hyprctl dispatch 'hl.dsp.focus({ monitor = "HDMI-A-1" })'
}