general {
    ignore_dbus_inhibit = false
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && sleep 1 && hyprctl dispatch 'hl.dsp.focus({ monitor = "HDMI-A-1" })'
}

listener {
    timeout = 600

    on-timeout = hyprctl eval 'hl.monitor({ output = "HDMI-A-1", disabled = true })' && hyprctl dispatch 'hl.dsp.dpms({ action = "disable", monitor = "HEADLESS-1" })'  && adb shell input keyevent 223

    on-resume = hyprctl eval 'hl.monitor({ output = "HDMI-A-1", disabled = false })' && hyprctl dispatch 'hl.dsp.dpms({ action = "enable", monitor = "HEADLESS-1" })' && sleep 1 && hyprctl dispatch 'hl.dsp.focus({ monitor = "HDMI-A-1" })' && adb shell input keyevent 224 && sleep 0.5 && adb shell wm dismiss-keyguard
}
