unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-s

set -g mouse on

set-option -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "catppuccin/tmux"
set -g @tmux-which-key-xdg-enable 1
set -g @plugin "alexwforsythe/tmux-which-key"
set -g @plugin "b0o/tmux-autoreload"

# Initialize tpack (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'