---
- name: Enable required system services
  become: true
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ systemd_system_services.enable | unique }}"
  loop_control:
    label: "{{ item }}"

- name: Enable required user services
  become: false
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    scope: user
  loop: "{{ systemd_user_services.enable | unique }}"
  loop_control:
    label: "{{ item }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"
  tags:
    - systemd-user-services

- name: Unmask shared user targets
  become: false
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    masked: false
    scope: user
  loop: "{{ systemd_user_targets.unmask | unique }}"
  loop_control:
    label: "{{ item }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"
  tags:
    - systemd-user-services

- name: Mask user targets
  become: false
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    masked: true
    scope: user
  loop: "{{ systemd_user_targets.mask | unique }}"
  loop_control:
    label: "{{ item }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"
  tags:
    - systemd-user-services

- name: Enable user targets
  become: false
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    scope: user
  loop: "{{ systemd_user_targets.enable | unique }}"
  loop_control:
    label: "{{ item }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_facts['user_uid'] }}"
  tags:
    - systemd-user-services
