# =============================================================================
# Module: prompt.zsh
# Purpose: Configure the interactive shell prompt appearance and prompt behavior.
# =============================================================================

# Load the local Powerlevel10k configuration generated by `p10k configure`.
[[ -r "$ZDOTDIR/.p10k.zsh" ]] && source "$ZDOTDIR/.p10k.zsh"
